blueprint:
  name: Aqara E1 Wireless Remote Switch (Single Rocker)(WXKG16LM) via Xiaomi Gateway 3
  description: Automate your Aqara E1 Wireless Remote Switch. [Working Feb 2023]
  domain: automation
  source_url: https://https://github.com/peccini/ha-blueprints/edit/main/xiaomi/wxkg16lm/wxkg16lm.yaml
  input:
    switch:
      name: Aqara E1 Wireless Remote Switc
      description: Select the _action entity of your switch here!
      selector:
        entity:
          integration: xiaomi_gateway3
          domain: sensor
    remote_button_single_press:
      name: Button Single
      description: Action to run on single press
      default: []
      selector:
        action: {}
trigger:
- platform: event
  event_type: state_changed
  event_data:
    entity_id: !input 'switch'
action:
- variables:
    action: '{{ trigger.event.data.new_state.state }}'
- choose:
  - conditions: '{{ action == ''single'' }}'
    sequence: !input 'remote_button_single_press'
